const ITN_Payload = {
    m_payment_id: 'SuperUnique1',
    pf_payment_id: '1089250',
    payment_status: 'COMPLETE',
    item_name: 'test+product',
    item_description: 'test+description',
    amount_gross: 200.0,
    amount_fee: -4.6,
    amount_net: 195.4,
    custom_str1: '',
    custom_str2: '',
    custom_str3: '',
    custom_str4: '',
    custom_str5: '',
    custom_int1: '',
    custom_int2: '',
    custom_int3: '',
    custom_int4: '',
    custom_int5: '',
    name_first: '',
    name_last: '',
    email_address: '',
    merchant_id: '10000100',
    signature: 'ad8e7685c9522c24365d7ccea8cb3db7',
}
