export const botsList = [
    {
        name: 'SWITCHER PRO',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/gl9agNNYKxA',
        botConfig: {
            stake: 2,
            martingale: 2,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'LOOP',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/gl9agNNYKxA',
        botConfig: {
            stake: 2,
            martingale: 6,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'QUANTUM SURGE PREMIUM',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/91ga38tRGwE',
        botConfig: {
            stake: 1,
            martingale: 3.5,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'TITAN EDGE',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/0IbMxj8wrw8',
        botConfig: {
            stake: 0.5,
            martingale: 2,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'DUAL STRIKE PREMIUM',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/m53oKD17GsY',
        botConfig: {
            stake: 2,
            martingale: 16,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'INFINITY PULSE',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/UE_OV9yTlTg',
        botConfig: {
            stake: 0.5,
            martingale: 2.5,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'THE ALPHA PREMIUM',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/fD1lRfV_YxA?si=NE8K2nDpcDTvECRe',
        botConfig: {
            stake: 1,
            martingale: 16,
            tp: 999,
            sl: 999,
        },
    },
    {
        name: 'ODDYSSEY PRO',
        summary: [''],
        amountInUSD: 499.99,
        isAvailableOnDemo: false,
        isPremium: false,
        tutorialLink: 'https://youtu.be/sF52eI-oYxs?si=YP0yMKd_qb6-A2RA',
        botConfig: {
            stake: 1,
            martingale: 2,
            tp: 999,
            sl: 999,
        },
    },
]
